### ISSUE TITLE
Climates of Ferngill: Improvements to core logic

### ISSUE THREAD

**Issue by JohnsonNicholas** [JohnsonNicholas/SDVMods#55]
Comments:

'll.. have to probably retrofit my fog mechanics into the .. climate object..
But I will be looking into that first, so I don't have to come up with a new climate json file beyond writing one
(Also, if it has a different climate, the big thing is: handling area transistions in terms of persistent weather)
but that'll be something interesting to work on

**Comment by JohnsonNicholas** [comment]
## 1.4 Planned Changes

Currently, we need to change several parts of the mod to work with SunDrop, and potentially allow for more customizable weather.

### Requirements for Sundrop

Sundrop wants it's own custom weather, and will have custom sounds. At the time of this writing, I dunno if it'll be anything but suntime or festival weather.

Sundrop's climate is San Francisco based, which will require some research but will more than likely have different even special weathers.

### To-Do List then

1. Investigate the current climate object
- [ ] Make sure the current climates are correct. Potentially build an WPF app to investigate and generate climates (as well as visualize them without having to use Excel)
- [ ] Determine what fields need to be added globally or within a weather segment.
2. Deal with location changes, especially if the climate has per location weather. 
- [ ] Should it be per location name, or is there a region stuff I should be adding..?
- [ ] The previous location data will need to be stored.
- [ ] Location changes may need to handle dropping the overlay (which should be automatic); and changing the music; etc. We can import the stuff from the console command
3. Miscellanous
- [ ] Look into fog coloration

**Comment by JohnsonNicholas** [comment]
Nope. I'm closing this, I'll return to it later.
